### ISSUE TITLE
Vector{?T} constructors

### ISSUE THREAD

**Issue by quinnj** [JuliaData/Nulls.jl#11]
It'd be convenient if we could have `Vector{?Int}(n)` return a vector with `null` instead of `#undef`. Not sure how feasible or serious it'd be to overload some of these methods, but worth looking into.

**Comment by quinnj** [comment]
Or we could at least provide a convenience method like `NullVector{Int}(n)` that just created a `Vector{?Int}(n)`

**Comment by nalimilan** [comment]
Overloading the constructor sounds a bit too much unfortunately. `NullVector` could work but it looks like a type, and introducing a type alias just for this is overkill; people would end up using it and `Vector{?Int}` inconsistently. Maybe a function `nulls` by analogy with `zeros`?

**Comment by quinnj** [comment]
ooo, I like `nulls`, that's a great idea.

**Comment by ararslan** [comment]
+1 for `nulls`, I love that.

Regard methods, perhaps there could be
```julia
nulls(dims...) = fill(null, dims)
nulls(T::Type, dims...) = convert(Array{Union{T, Null}}, fill(null, dims))
```
The former creates an array with element type `Null` whereas the latter ensures that we have the desired `Union`.

**Comment by nalimilan** [comment]
To avoid unnecessary copies, I guess the second definition should be something like
```julia
nulls(T::Type, dims...) = fill!(Array{Union{T, Null}}(dims), null)
```
