### ISSUE TITLE
minmax, extrema, divrem, reim, and friends

### ISSUE THREAD

**Issue by TotalVerb** [JuliaData/Nulls.jl#18]
What's the plan for

```julia
minmax(Null(), Null())
extrema(Null())
divrem(Null(), Null())
reim(Null())
```

and similar functions? I can see an argument for either `Null()` or `(Null(), Null())`.

**Comment by ararslan** [comment]
I think just `null` would be really annoying; any code that did something like `a, b = extrema(x)` would then fail in the presence of missing data, whereas the point of having this propagating null value is that it blends more naturally into typical workflows. So I'd definitely vote for `(null, null)` for these.

**Comment by nalimilan** [comment]
Have you tried it? That already works:
```julia
julia> using Nulls

julia> extrema(null)
(null, null)

julia> minmax(null, null)
(null, null)

julia> divrem(null, null)
(null, null)
```

Only `reim` fails because `real(null)` doesn't work (should it?).

**Comment by TotalVerb** [comment]
Indeed it does already work. However, with the long-term plan to lift more functions, I was wondering whether that was by oversight (i.e. these functions hadn't been defined as lifting yet) or design.

**Comment by nalimilan** [comment]
I think the idea is that everywhere it's possible, we will rely on the basic definitions of operators (like `<` for `extrema`). This will offer a fully consistent behavior. This may require broadening some signatures in Base, notably replacing `Array{<:Real}` with `Array{<:?Real}`, which will only be possible once `Null` will be defined in Base.

Skipping nulls will require explicitly using something like `Nulls.skip`; maybe we'll need to find something more convenient (cf. [my comment](https://github.com/JuliaData/Nulls.jl/pull/15#issuecomment-304518733)).

Can this be closed? Or do you want to investigate the `real(null)` issue?

**Comment by TotalVerb** [comment]
Sure. `real(null) === null` makes sense, but that's a separate issue.
