### ISSUE TITLE
README mistake?

### ISSUE THREAD

**Issue by mauro3** [JuliaData/Nulls.jl#35]
It claims in the README that "that it [`null`] essentially becomes a NaN for any type".  IMO, one essential feature of NaN is `NaN==NaN` returns `false`.  This is not the case for `null`.  Maybe this should be clarified?

**Comment by cjprybol** [comment]
This behavior changed in https://github.com/JuliaData/Nulls.jl/pull/33. You're correct that the README is now wrong for the master branch. The `NaN` behavior is still in place for the latest release, however.

**Comment by ararslan** [comment]
Actually `null == null` is no longer `true`, as of a recent PR; it's now `null`.

**Comment by nalimilan** [comment]
Good catch. I've filed https://github.com/JuliaData/Nulls.jl/pull/36, taking the occasion to develop and update the docs.
